-- SQL Migration: Add Saved POIs and Content tables

-- 1. Table for individual saved POIs (independent of routes)
CREATE TABLE IF NOT EXISTS public.saved_pois (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    poi_id TEXT NOT NULL, -- Stable ID generated by our frontend
    poi_data JSONB NOT NULL, -- Snapshot of name, coords, category, narrative
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, poi_id)
);

-- Enable RLS for saved_pois
ALTER TABLE public.saved_pois ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own saved POIs" 
    ON public.saved_pois 
    FOR ALL 
    USING (auth.uid() = user_id);

-- 2. Table for route content (comments, photos) - Future Expansion
CREATE TABLE IF NOT EXISTS public.route_content (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    route_id TEXT NOT NULL, -- Can be a curated_route ID or saved_route UUID
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content_type TEXT NOT NULL CHECK (content_type IN ('comment', 'photo')),
    content_body TEXT NOT NULL, -- Comment text or Image URL
    metadata JSONB DEFAULT '{}'::jsonb, -- Additional info like photo caption
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for route_content
ALTER TABLE public.route_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view route content" 
    ON public.route_content 
    FOR SELECT 
    USING (true);

CREATE POLICY "Users can manage their own route content" 
    ON public.route_content 
    FOR ALL 
    USING (auth.uid() = user_id);

-- 3. Optimization: Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_saved_pois_user ON public.saved_pois(user_id);
CREATE INDEX IF NOT EXISTS idx_route_content_route ON public.route_content(route_id);
